sudo: required
services:
  - docker

before_install:
  - docker build -t nadjibdeveloper/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nadjibdeveloper/react-test npm test -- --coverage

after_success:
  - docker build -t nadjibdeveloper/multi-client ./client
  - docker build -t nadjibdeveloper/multi-nginx ./nginx
  - docker build -t nadjibdeveloper/multi-server ./server
  - docker build -t nadjibdeveloper/multi-worker ./worker
#Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nadjibdeveloper/multi-client
  - docker push nadjibdeveloper/multi-nginx
  - docker push nadjibdeveloper/multi-server
  - docker push nadjibdeveloper/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-742424968078'
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
